# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersaccount',
            name='social_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
