# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersaccount_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
