# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180906_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersaccount',
            name='social_account',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='client',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='username',
        ),
    ]
