# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('gs_points', models.IntegerField()),
                ('gs_points_given', models.IntegerField()),
                ('gs_points_redeemed', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Clients')),
            ],
        ),
    ]
