# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_discounts_gallery_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsprofile',
            name='banner',
            field=models.ImageField(default='home/dk/Desktop/gluespark/static/img/bg1.jpg', upload_to=''),
        ),
    ]
