# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopsprofile_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts',
            old_name='gs_points',
            new_name='ady_points',
        ),
        migrations.RenameField(
            model_name='shopsprofile',
            old_name='gs_points',
            new_name='ady_points',
        ),
        migrations.RenameField(
            model_name='shopsprofile',
            old_name='gs_points_given',
            new_name='ady_points_given',
        ),
        migrations.RenameField(
            model_name='shopsprofile',
            old_name='gs_points_redeemed',
            new_name='ady_points_redeemed',
        ),
    ]
