# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20180907_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopsProfile',
            new_name='StoreProfile',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='shop',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='shop',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='shop',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storeprofile',
            old_name='shop',
            new_name='store',
        ),
    ]
