# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180816_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comment',
            field=models.CharField(default='no data for now', max_length=300),
        ),
    ]
