# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersaccount_social_account'),
        ('reviews', '0004_reviews_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.IntegerField()),
                ('rating', models.FloatField()),
                ('food_quality', models.FloatField()),
                ('value_for_money', models.FloatField()),
                ('hygiene', models.FloatField()),
                ('service', models.FloatField()),
                ('comment', models.CharField(default='no data for now', max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Clients')),
            ],
        ),
    ]
