# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0003_shopsprofile_banner'),
        ('reviews', '0005_tempreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponsAvailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reward_points', models.IntegerField(default=0)),
                ('used', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shops.ShopsProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
