# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_couponsavailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponsavailed',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='couponsavailed',
            name='user',
        ),
        migrations.DeleteModel(
            name='CouponsAvailed',
        ),
    ]
