# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20180909_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='client',
            new_name='store',
        ),
    ]
